name: Rebuild Distribution

on:
  push:
    branches:
      - '7.9.2'
    paths:
      - 'Extensions/*'
      - 'Themes/*'

jobs:
  build:
    name: Autobuild extensions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Install gulp-cli
        run: npm install gulp-cli

      - name: Build distribution
        run: gulp build

      - name: Push changes to gh-pages
        run: >
          npx gh-pages
            --add
            --dist .
            --src "{Extensions/dist/*.json,Extensions/dist/page/gallery.json,Extensions/dist/page/list.json,Extensions/dist/page/themes.json}"
            --message 'Rebuild Distribution'
