name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find latest tag
        id: find-tag
        run: |
          tag=$(git describe --tags --abbrev=0)
          echo tag=$tag >> $GITHUB_OUTPUT
          echo cleantag=${tag/v/} >> $GITHUB_OUTPUT

      - name: Checkout latest tag
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.find-tag.outputs.tag }}
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      # - name: Firefox — Download signed XPI file
      #   run: node dev/download_xpi.mjs

      - name: "MOCK: Firefox — Download signed XPI file"
        run: |
          node -e "import fs from 'node:fs'; fs.mkdirSync('web-ext-artifacts', { recursive: true }); fs.writeFileSync('web-ext-artifacts/whatever-7.10.0.xpi', 'hello world');"

      - name: Generate Github Release
        uses: softprops/action-gh-release@v2
        with:
          name: New XKit ${{ steps.find-tag.outputs.cleantag }}
          tag_name: ${{ steps.find-tag.outputs.tag }}
          generate_release_notes: true
          body: |
            **NOTE:** Firefox may complain about getting a connection error when clicking the below XPI link. If it does, right-click the link and select "Save Link As...", then navigate to `about:addons` and drag the file onto that screen to install New XKit.

            For Chrome: Install from the [Chrome Web Store](https://new-xkit-extension.tumblr.com/chrome) instead of here.
          files: web-ext-artifacts/*.xpi
          draft: true
